# Generated by Django 5.2.7 on 2026-09-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estadio', models.CharField(default='Estadio Mella 1', max_length=100)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('envivo', 'En vivo'), ('final', 'Final')], default='programado', max_length=20)),
                ('carreras_local', models.PositiveIntegerField(default=0)),
                ('carreras_visita', models.PositiveIntegerField(default=0)),
                ('inning_actual', models.CharField(default='1RA ALTA', max_length=20)),
                ('outs', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Jugada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.CharField(default='1', max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('hit', 'Hit'), ('out', 'Out'), ('carrera', 'Carrera'), ('bb', 'Base por bola'), ('hr', 'Home Run'), ('error', 'Error'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('temporada', models.CharField(default='Apertura 2026', max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
