# Generated by Django 5.2.7 on 2026-09-20 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_equipo_banner_jugador_apellido_jugador_ci_and_more'),
        ('torneos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganados', models.PositiveIntegerField(default=0)),
                ('perdidos', models.PositiveIntegerField(default=0)),
                ('ca', models.PositiveIntegerField(default=0, verbose_name='Carreras anotadas')),
                ('cp', models.PositiveIntegerField(default=0, verbose_name='Carreras permitidas')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='equipos.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='torneos.torneo')),
            ],
            options={
                'unique_together': {('equipo', 'torneo')},
            },
        ),
    ]
