# Generated by Django 5.2.7 on 2026-09-20 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_equipo_banner_jugador_apellido_jugador_ci_and_more'),
        ('torneos', '0003_equipotorneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='bolas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='juego',
            name='idx_local',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='juego',
            name='idx_visita',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='juego',
            name='inning_num',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='juego',
            name='mitad',
            field=models.CharField(choices=[('alta', 'Alta'), ('baja', 'Baja')], default='alta', max_length=10),
        ),
        migrations.AddField(
            model_name='juego',
            name='pitcher_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juegos_pitcheados_local', to='equipos.jugador'),
        ),
        migrations.AddField(
            model_name='juego',
            name='pitcher_visita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juegos_pitcheados_visita', to='equipos.jugador'),
        ),
        migrations.AddField(
            model_name='juego',
            name='strikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugada',
            name='bateador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='equipos.jugador'),
        ),
        migrations.AddField(
            model_name='jugada',
            name='carreras',
            field=models.PositiveIntegerField(default=0, verbose_name='Carreras en la jugada'),
        ),
        migrations.AddField(
            model_name='jugada',
            name='d_ab',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugada',
            name='d_bb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugada',
            name='d_h',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugada',
            name='d_h2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugada',
            name='d_h3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugada',
            name='d_hbp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugada',
            name='d_hr',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugada',
            name='d_kpit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugada',
            name='d_r',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugada',
            name='d_rbi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugada',
            name='d_sf',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugada',
            name='equipo_batea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_bateo', to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='jugada',
            name='inning_num',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jugada',
            name='mitad',
            field=models.CharField(default='alta', max_length=10),
        ),
        migrations.AddField(
            model_name='jugada',
            name='pitcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_pitcheados', to='equipos.jugador'),
        ),
        migrations.AddField(
            model_name='jugada',
            name='rbi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugada',
            name='resultado',
            field=models.CharField(choices=[('hit', 'Hit sencillo'), ('doble', 'Doble (2B)'), ('triple', 'Triple (3B)'), ('hr', 'Home Run'), ('out', 'Out'), ('k', 'Ponche (K)'), ('bb', 'Base por bola'), ('hbp', 'Golpeado'), ('sf', 'Sacrificio'), ('error', 'Error'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AddField(
            model_name='jugada',
            name='s_bolas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugada',
            name='s_cl',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugada',
            name='s_cv',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugada',
            name='s_idx',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugada',
            name='s_inning',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jugada',
            name='s_mitad',
            field=models.CharField(default='alta', max_length=10),
        ),
        migrations.AddField(
            model_name='jugada',
            name='s_outs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugada',
            name='s_strikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('carreras_local', models.PositiveIntegerField(default=0)),
                ('carreras_visita', models.PositiveIntegerField(default=0)),
                ('hits_local', models.PositiveIntegerField(default=0)),
                ('hits_visita', models.PositiveIntegerField(default=0)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='torneos.juego')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('juego', 'numero')},
            },
        ),
    ]
