# Generated by Django 5.2.7 on 2026-09-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0004_juego_bolas_juego_idx_local_juego_idx_visita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='fase',
            field=models.CharField(choices=[('regular', 'Regular'), ('semifinal', 'Semifinal'), ('final', 'Final')], default='regular', max_length=20, verbose_name='Fase'),
        ),
        migrations.AddField(
            model_name='juego',
            name='serie',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Serie (SF1/SF2/F)'),
        ),
    ]
