# Generated by Django 5.2.7 on 2026-09-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0005_juego_fase_juego_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='playoffs_activos',
            field=models.BooleanField(default=False, verbose_name='Playoffs activos (visible en la página)'),
        ),
    ]
