# Generated by Django 5.2.7 on 2026-10-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0007_alter_jugada_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugada',
            name='resultado',
            field=models.CharField(choices=[('hit', 'Hit sencillo'), ('doble', 'Doble (2B)'), ('triple', 'Triple (3B)'), ('hr', 'Home Run'), ('out', 'Out'), ('k', 'Ponche (K)'), ('bb', 'Base por bola'), ('hbp', 'Golpeado'), ('sf', 'Sacrificio'), ('error', 'Error'), ('fc', "Fielder's Choice (FC)"), ('dp', 'Doble play (DP)'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
