# Generated by Django 5.2.7 on 2026-10-05 23:23

from django.db import migrations, models


def _normalizar_flags(apps, schema_editor):
    Juego = apps.get_model('torneos', 'Juego')
    Juego.objects.filter(estado='final').update(resultado_aplicado=True)
    Juego.objects.exclude(estado='final').update(resultado_aplicado=False)


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0008_alter_jugada_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='resultado_aplicado',
            field=models.BooleanField(default=False, verbose_name='Resultado aplicado a la tabla'),
        ),
        migrations.RunPython(_normalizar_flags, migrations.RunPython.noop),
    ]
