# Generated by Django 5.2.7 on 2026-09-20 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fichaje_recibido', 'Fichaje recibido'), ('fichaje_aceptado', 'Fichaje aceptado'), ('fichaje_rechazado', 'Fichaje rechazado'), ('resultado', 'Resultado de juego'), ('posicion', 'Cambio de posición'), ('sistema', 'Sistema')], default='sistema', max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.CharField(blank=True, max_length=300)),
                ('url', models.CharField(blank=True, default='', max_length=300)),
                ('leida', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
    ]
