# Generated by Django 5.2.7 on 2026-09-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField()),
                ('cuerpo', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('torneo_tag', models.CharField(default='TORNEO APERTURA', max_length=100)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
