# Generated by Django 5.2.7 on 2026-09-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_noticia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagen intermedia'),
        ),
    ]
