# Generated by Django 5.2.7 on 2026-09-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_noticia_imagen2'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='video_facebook',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Video de Facebook (URL)'),
        ),
    ]
