# Generated by Django 5.2.7 on 2026-10-05 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0010_equipo_abierto'),
        ('torneos', '0006_torneo_playoffs_activos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sustitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sustitucion', 'Sustitución'), ('swap_pos', 'Swap defensivo')], default='sustitucion', max_length=20)),
                ('orden_sale', models.PositiveIntegerField(blank=True, null=True)),
                ('orden_entra', models.PositiveIntegerField(blank=True, null=True)),
                ('pos_sale_old', models.CharField(blank=True, default='', max_length=5)),
                ('pos_sale_new', models.CharField(blank=True, default='', max_length=5)),
                ('pos_entra_old', models.CharField(blank=True, default='', max_length=5)),
                ('pos_entra_new', models.CharField(blank=True, default='', max_length=5)),
                ('inning_num', models.PositiveIntegerField(default=1)),
                ('mitad', models.CharField(default='alta', max_length=10)),
                ('s_idx', models.PositiveIntegerField(default=0)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('entra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_entrada', to='equipos.jugador')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='equipos.equipo')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='torneos.juego')),
                ('jugada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sustitucion', to='torneos.jugada')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_salida', to='equipos.jugador')),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
    ]
