# Generated by Django 5.2.7 on 2026-09-19 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estadisticas', '0001_initial'),
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liderato',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneos.torneo'),
        ),
    ]
