# Generated by Django 5.2.7 on 2026-09-20 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_equipo_banner_jugador_apellido_jugador_ci_and_more'),
        ('estadisticas', '0002_initial'),
        ('torneos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuacionBateo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab', models.PositiveIntegerField(default=0, verbose_name='Turnos (AB)')),
                ('r', models.PositiveIntegerField(default=0, verbose_name='Anotadas (R)')),
                ('h', models.PositiveIntegerField(default=0, verbose_name='Hits (H)')),
                ('h2', models.PositiveIntegerField(default=0, verbose_name='Dobles (2B)')),
                ('h3', models.PositiveIntegerField(default=0, verbose_name='Triples (3B)')),
                ('hr', models.PositiveIntegerField(default=0, verbose_name='Jonrones (HR)')),
                ('rbi', models.PositiveIntegerField(default=0, verbose_name='Impulsadas (RBI)')),
                ('sb', models.PositiveIntegerField(default=0, verbose_name='Robadas (SB)')),
                ('bb', models.PositiveIntegerField(default=0, verbose_name='Boletos (BB)')),
                ('hbp', models.PositiveIntegerField(default=0, verbose_name='Golpeados (HBP)')),
                ('sf', models.PositiveIntegerField(default=0, verbose_name='Sacrificios (SF)')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='equipos.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bateo', to='torneos.torneo')),
            ],
            options={
                'unique_together': {('jugador', 'torneo')},
            },
        ),
    ]
