# Generated by Django 5.2.7 on 2026-09-20 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_equipo_banner_jugador_apellido_jugador_ci_and_more'),
        ('estadisticas', '0003_actuacionbateo'),
        ('torneos', '0003_equipotorneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuacionbateo',
            name='k',
            field=models.PositiveIntegerField(default=0, verbose_name='Ponches (K)'),
        ),
        migrations.CreateModel(
            name='ActuacionPitcheo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jl', models.PositiveIntegerField(default=0, verbose_name='Juegos lanzados')),
                ('ip_outs', models.PositiveIntegerField(default=0, verbose_name='Outs registrados')),
                ('k', models.PositiveIntegerField(default=0, verbose_name='Ponches (K)')),
                ('bb', models.PositiveIntegerField(default=0, verbose_name='Boletos')),
                ('h', models.PositiveIntegerField(default=0, verbose_name='Hits permitidos')),
                ('r', models.PositiveIntegerField(default=0, verbose_name='Carreras')),
                ('er', models.PositiveIntegerField(default=0, verbose_name='Limpias')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitcheo', to='equipos.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitcheo', to='torneos.torneo')),
            ],
            options={
                'unique_together': {('jugador', 'torneo')},
            },
        ),
    ]
