# Generated by Django 5.2.7 on 2026-09-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0004_actuacionbateo_k_actuacionpitcheo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuacionbateo',
            name='rbi',
            field=models.PositiveIntegerField(default=0, verbose_name='Carreras impulsadas (CI)'),
        ),
        migrations.AlterField(
            model_name='actuacionbateo',
            name='sb',
            field=models.PositiveIntegerField(default=0, verbose_name='Robadas (SB, en desuso)'),
        ),
    ]
