# Generated by Django 5.2.7 on 2026-09-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ci',
            field=models.CharField(blank=True, max_length=30, verbose_name='Carnet de identidad'),
        ),
        migrations.AddField(
            model_name='user',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='estatura',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
