# Generated by Django 5.2.7 on 2026-09-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_user_ci_user_edad_user_estatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('capitan', 'Capitán'), ('director', 'Director'), ('anotador', 'Anotador'), ('fan', 'Aficionado')], default='fan', max_length=20),
        ),
    ]
