# Generated by Django 5.2.7 on 2026-09-20 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0004_equipo_banner_jugador_apellido_jugador_ci_and_more'),
        ('torneos', '0003_equipotorneo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alineacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones', to='equipos.equipo')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones', to='torneos.juego')),
            ],
            options={
                'ordering': ['-actualizada'],
                'unique_together': {('equipo', 'juego')},
            },
        ),
        migrations.CreateModel(
            name='PlantillaAlineacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='equipos.equipo')),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='AlineacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'Primera'), ('2B', 'Segunda'), ('SS', 'Shortstop'), ('3B', 'Tercera'), ('LF', 'Left Field'), ('LCF', 'Left-Center'), ('RCF', 'Right-Center'), ('RF', 'Right Field')], max_length=5)),
                ('orden_bateo', models.PositiveIntegerField(verbose_name='Turno al bate (1,2,3...)')),
                ('alineacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='capitanes.alineacion')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones_det', to='equipos.jugador')),
            ],
            options={
                'ordering': ['orden_bateo'],
                'unique_together': {('alineacion', 'jugador'), ('alineacion', 'orden_bateo'), ('alineacion', 'posicion')},
            },
        ),
        migrations.CreateModel(
            name='PlantillaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'Primera'), ('2B', 'Segunda'), ('SS', 'Shortstop'), ('3B', 'Tercera'), ('LF', 'Left Field'), ('LCF', 'Left-Center'), ('RCF', 'Right-Center'), ('RF', 'Right Field')], max_length=5)),
                ('orden_bateo', models.PositiveIntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.jugador')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='capitanes.plantillaalineacion')),
            ],
            options={
                'ordering': ['orden_bateo'],
                'unique_together': {('plantilla', 'jugador'), ('plantilla', 'orden_bateo'), ('plantilla', 'posicion')},
            },
        ),
    ]
