# Generated by Django 5.2.7 on 2026-09-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitanes', '0001_initial'),
        ('equipos', '0004_equipo_banner_jugador_apellido_jugador_ci_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alineaciondetalle',
            unique_together={('alineacion', 'jugador'), ('alineacion', 'orden_bateo')},
        ),
        migrations.AlterUniqueTogether(
            name='plantilladetalle',
            unique_together={('plantilla', 'jugador'), ('plantilla', 'orden_bateo')},
        ),
        migrations.AlterField(
            model_name='alineaciondetalle',
            name='orden_bateo',
            field=models.PositiveIntegerField(verbose_name='Turno al bate (1..15)'),
        ),
        migrations.AlterField(
            model_name='alineaciondetalle',
            name='posicion',
            field=models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'Primera'), ('2B', 'Segunda'), ('SS', 'Shortstop'), ('3B', 'Tercera'), ('LF', 'Left Field'), ('LCF', 'Left-Center'), ('RCF', 'Right-Center'), ('RF', 'Right Field'), ('EH', 'Extra Hitter'), ('BD', 'Bateador Designado')], max_length=5),
        ),
        migrations.AlterField(
            model_name='plantilladetalle',
            name='posicion',
            field=models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'Primera'), ('2B', 'Segunda'), ('SS', 'Shortstop'), ('3B', 'Tercera'), ('LF', 'Left Field'), ('LCF', 'Left-Center'), ('RCF', 'Right-Center'), ('RF', 'Right Field'), ('EH', 'Extra Hitter'), ('BD', 'Bateador Designado')], max_length=5),
        ),
    ]
