# Generated by Django 5.2.7 on 2026-09-21 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitanes', '0002_alter_alineaciondetalle_unique_together_and_more'),
        ('equipos', '0006_equipo_banner_x_equipo_banner_y'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlineacionTitular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='titular', to='equipos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='TitularDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'Primera'), ('2B', 'Segunda'), ('SS', 'Shortstop'), ('3B', 'Tercera'), ('LF', 'Left Field'), ('LCF', 'Left-Center'), ('RCF', 'Right-Center'), ('RF', 'Right Field')], max_length=5)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titular_det', to='equipos.jugador')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='capitanes.alineaciontitular')),
            ],
            options={
                'unique_together': {('titular', 'jugador'), ('titular', 'posicion')},
            },
        ),
    ]
