# Generated by Django 5.2.7 on 2026-09-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitanes', '0003_alineaciontitular_titulardetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alineaciondetalle',
            name='orden_bateo',
            field=models.PositiveIntegerField(verbose_name='Turno al bate (1..16)'),
        ),
        migrations.AlterField(
            model_name='alineaciondetalle',
            name='posicion',
            field=models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'Primera'), ('2B', 'Segunda'), ('SS', 'Shortstop'), ('3B', 'Tercera'), ('LF', 'Left Field'), ('LCF', 'Left-Center'), ('RCF', 'Right-Center'), ('RF', 'Right Field'), ('EH', 'Extra Hitter'), ('BD', 'Bateador Designado'), ('BA', 'Bateador Asignado')], max_length=5),
        ),
        migrations.AlterField(
            model_name='plantilladetalle',
            name='posicion',
            field=models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'Primera'), ('2B', 'Segunda'), ('SS', 'Shortstop'), ('3B', 'Tercera'), ('LF', 'Left Field'), ('LCF', 'Left-Center'), ('RCF', 'Right-Center'), ('RF', 'Right Field'), ('EH', 'Extra Hitter'), ('BD', 'Bateador Designado'), ('BA', 'Bateador Asignado')], max_length=5),
        ),
    ]
