# Generated by Django 5.2.7 on 2026-09-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitanes', '0004_alter_alineaciondetalle_orden_bateo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulardetalle',
            name='posicion',
            field=models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'Primera'), ('2B', 'Segunda'), ('SS', 'Shortstop'), ('3B', 'Tercera'), ('LF', 'Left Field'), ('LCF', 'Left-Center'), ('RCF', 'Right-Center'), ('RF', 'Right Field'), ('BD', 'Bateador Designado'), ('BA1', 'Asignado 1'), ('BA2', 'Asignado 2'), ('BA3', 'Asignado 3'), ('BA4', 'Asignado 4'), ('BA5', 'Asignado 5')], max_length=5),
        ),
    ]
