# Generated by Django 5.2.7 on 2026-10-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitanes', '0005_alter_titulardetalle_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alineacion',
            name='pitcher_batea',
            field=models.BooleanField(default=True, verbose_name='El pitcher batea'),
        ),
    ]
