# Generated by Django 5.2.7 on 2026-09-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(max_length=5)),
                ('color', models.CharField(default='#0A1A3A', max_length=20)),
                ('victorias', models.PositiveIntegerField(default=0)),
                ('derrotas', models.PositiveIntegerField(default=0)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='equipos/')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dorsal', models.PositiveIntegerField(default=0)),
                ('posicion', models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'Primera'), ('2B', 'Segunda'), ('SS', 'Shortstop'), ('3B', 'Tercera'), ('LF', 'Left Field'), ('LCF', 'Left-Center'), ('RCF', 'Right-Center'), ('RF', 'Right Field')], default='P', max_length=5)),
                ('es_capitan', models.BooleanField(default=False)),
                ('avg', models.FloatField(default=0)),
                ('hr', models.PositiveIntegerField(default=0)),
                ('rbi', models.PositiveIntegerField(default=0)),
                ('era', models.FloatField(blank=True, default=0)),
            ],
            options={
                'ordering': ['dorsal'],
            },
        ),
    ]
