# Generated by Django 5.2.7 on 2026-09-20 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_jugador_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='equipos/banners/'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jugador',
            name='ci',
            field=models.CharField(blank=True, max_length=30, verbose_name='Carnet de identidad'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='estatura',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='jugador',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ficha_jugador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='dorsal',
            field=models.PositiveIntegerField(default=0, verbose_name='Núm. chaparreta'),
        ),
        migrations.CreateModel(
            name='SolicitudTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='equipos.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
    ]
