# Generated by Django 5.2.7 on 2026-09-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_equipo_banner_jugador_apellido_jugador_ci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtraslado',
            name='mensaje',
            field=models.TextField(blank=True, verbose_name='Mensaje del capitán'),
        ),
    ]
