# Generated by Django 5.2.7 on 2026-09-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_solicitudtraslado_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='banner_x',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Encuadre horizontal %'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='banner_y',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Encuadre vertical %'),
        ),
    ]
