# Generated by Django 5.2.7 on 2026-09-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0006_equipo_banner_x_equipo_banner_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='rbi',
            field=models.PositiveIntegerField(default=0, verbose_name='Carreras impulsadas (CI)'),
        ),
    ]
