# Generated by Django 5.2.7 on 2026-09-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0007_alter_jugador_rbi'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='jugadores/portadas/', verbose_name='Foto de portada'),
        ),
    ]
