# Generated by Django 5.2.7 on 2026-09-29 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0008_jugador_portada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_dirigidos', to=settings.AUTH_USER_MODEL, verbose_name='Director (mismo poder que el capitán)'),
        ),
    ]
