# Generated by Django 5.2.7 on 2026-10-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0009_equipo_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='abierto',
            field=models.BooleanField(default=True, verbose_name='Acepta nuevos jugadores'),
        ),
    ]
